# Auto-generated by WLA experiments/robotwin adapter.
# This file is copied into a RoboTwin checkout by run_robotwin_eval.py.

import os
import sys


current_file_path = os.path.abspath(__file__)
parent_directory = os.path.dirname(current_file_path)
if parent_directory not in sys.path:
    sys.path.insert(0, parent_directory)

from robotwin_utils import WLARoboTwinPolicy


def get_model(usr_args):
    return WLARoboTwinPolicy.from_usr_args(usr_args)


def eval(TASK_ENV, model, observation):
    model.eval_step(TASK_ENV, observation)


def reset_model(model):
    model.reset()

