# Auto-generated by WLA experiments/robotwin adapter.
# This file is copied into a RoboTwin checkout by run_robotwin_eval.py.

import json
import os
import sys
from pathlib import Path
from typing import Any, Optional

import numpy as np
import torch
from torchvision.transforms.functional import to_tensor


def _get_arg(args: dict[str, Any], key: str, default: Any = None) -> Any:
    value = args.get(key, default)
    return default if value is None else value


def _as_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y", "on"}
    return bool(value)


def _as_optional_path(value: Any) -> Optional[str]:
    if value in {None, "", "None", "none", "null"}:
        return None
    return str(value)


def _resolve_wla_root(args: dict[str, Any]) -> Path:
    raw_root = os.environ.get("WLA_ROOT") or args.get("wla_root")
    if not raw_root:
        raise RuntimeError(
            "WLA_ROOT is not set. Run through experiments/robotwin/run_robotwin_eval.py "
            "so the adapter can import the WLA model code."
        )

    root = Path(raw_root).expanduser().resolve()
    if not (root / "models" / "wla.py").is_file():
        raise FileNotFoundError(f"Invalid WLA root: {root}")
    return root


def _resolve_file(path_value: Any, wla_root: Path, *, default: Optional[str] = None) -> Optional[str]:
    path = _as_optional_path(path_value if path_value is not None else default)
    if path is None:
        return None

    expanded = Path(path).expanduser()
    if expanded.is_absolute():
        return str(expanded)

    wla_candidate = wla_root / expanded
    if wla_candidate.exists():
        return str(wla_candidate)

    cwd_candidate = Path.cwd() / expanded
    if cwd_candidate.exists():
        return str(cwd_candidate)

    return str(wla_candidate)


def _resolve_model_id(model_id: str, wla_root: Path) -> str:
    expanded = Path(model_id).expanduser()
    if expanded.is_absolute():
        return str(expanded)

    wla_candidate = wla_root / expanded
    if wla_candidate.exists():
        return str(wla_candidate)

    cwd_candidate = Path.cwd() / expanded
    if cwd_candidate.exists():
        return str(cwd_candidate)

    return model_id


def _import_wla_modules(wla_root: Path):
    root = str(wla_root)
    if root not in sys.path:
        sys.path.insert(0, root)

    from models.wla import WLA
    from utils.transforms import _make_transform, normalize_and_pad, unnormalize_and_unpad

    return WLA, _make_transform, normalize_and_pad, unnormalize_and_unpad


def _to_list(value: Any) -> list[float]:
    return np.asarray(value, dtype=np.float32).reshape(-1).tolist()


def _required_arg(args: dict[str, Any], key: str) -> Any:
    value = _get_arg(args, key)
    if value in {None, "", "None", "none", "null"}:
        raise ValueError(f"{key} is required. Pass --{key} or set the matching environment variable.")
    return value


def _validate_control_mode(control_mode: str) -> str:
    control_mode = control_mode.lower()
    if control_mode not in {"eef", "joint"}:
        raise ValueError(f"Unsupported control_mode: {control_mode}. Expected 'eef' or 'joint'.")
    return control_mode


def _configure_eval_observation(task_env) -> bool:
    # Every guard below marks a consumer of frames the model itself never reads:
    # video needs one frame per action, save_data is the TTT collection path,
    # render_freq drives the viewer, and crazy_random_light re-randomises the
    # lights inside _update_render(), so skipping renders there would change both
    # the images the model sees and the global RNG consumption order.
    return (
        os.environ.get("ROBOTWIN_FAST_EVAL") == "1"
        and task_env.eval_video_path is None
        and not task_env.save_data
        and task_env.render_freq == 0
        and not task_env.crazy_random_light
    )


def _post_action_observation_indices(
    action_count: int,
    history_obs_step: int,
    fast_eval: bool,
) -> range | tuple[int, ...]:
    # WLA consumes only the first frame of each action chunk, so every other
    # post-action observation is dead weight during evaluation. The one exception
    # is the frame that becomes the next chunk's history observation: with
    # chunk_size=32 and history_obs_step=8 that is action index 23. The index is
    # derived from action_count and clamped exactly like the full path, so a
    # truncated chunk still selects the frame full mode would have kept.
    #
    # Equivalence is asserted by unit tests on the physical-step and
    # check_success() counts and on the selected history frame -- NOT by
    # comparing action counts across rollouts. With control_mode="eef" every
    # chunk calls the cuRobo planner, which draws its trajectory seeds in its own
    # CUDA context outside torch/numpy/random seeding, so the action count varies
    # between identical reruns. Measured: 8 identical-config repeats of seed
    # 100000 gave 448/446/446/446/448/446/448/446.
    if not fast_eval:
        return range(action_count)
    if action_count == 0:
        return ()
    return (max(action_count - history_obs_step - 1, 0),)


class WLARoboTwinPolicy:
    def __init__(
        self,
        *,
        wla_root: Path,
        model_id: str,
        checkpoints_dir: Optional[str],
        norm_file_path: str,
        unnorm_key: str,
        control_mode: str,
        max_state_dim: int,
        original_action_dim: int,
        target_image_size: int = 512,
        vae_downsample_f: int = 32,
        primary_image_size: int = 256,
        auxiliary_image_size: int = 256,
        action_chunk_size: Optional[int] = None,
        strip_world_model: bool = True,
        dtype: str = "bfloat16",
    ):
        WLA, make_transform, normalize_and_pad, unnormalize_and_unpad = _import_wla_modules(wla_root)
        self.make_transform = make_transform
        self.normalize_and_pad = normalize_and_pad
        self.unnormalize_and_unpad = unnormalize_and_unpad

        self.control_mode = control_mode
        self.wla_root = wla_root
        self.max_state_dim = max_state_dim
        self.original_action_dim = original_action_dim
        self.primary_image_size = primary_image_size
        self.auxiliary_image_size = auxiliary_image_size
        self.history_obs_step = 8
        self.action_chunk_size = action_chunk_size
        self.history_observation = None

        with open(norm_file_path, "r", encoding="utf-8") as f:
            norm_stats = json.load(f)
        if unnorm_key not in norm_stats:
            available = ", ".join(sorted(norm_stats.keys()))
            raise KeyError(f"Normalization key '{unnorm_key}' not found. Available keys: {available}")
        self.norm_stats = norm_stats[unnorm_key]

        input_size = target_image_size // vae_downsample_f
        print(f"Loading WLA model from: {model_id}")
        self.model = WLA.from_pretrained(model_id, input_size=input_size)

        if checkpoints_dir:
            checkpoint_path = Path(checkpoints_dir).expanduser() / "model.pt"
            print(f"Loading WLA checkpoint from: {checkpoint_path}")
            state_dict = torch.load(str(checkpoint_path), map_location="cpu")
            self.model.load_state_dict(state_dict)

        config_history_obs_step = getattr(self.model.config, "history_obs_step", None)
        if config_history_obs_step is not None:
            self.history_obs_step = int(config_history_obs_step)

        if strip_world_model:
            self._strip_unused_modules()

        torch_dtype = getattr(torch, dtype)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = self.model.to(device=device, dtype=torch_dtype)
        self.model.eval()

    @classmethod
    def from_usr_args(cls, usr_args: dict[str, Any]):
        wla_root = _resolve_wla_root(usr_args)
        control_mode = _validate_control_mode(str(_required_arg(usr_args, "control_mode")))

        model_id = _get_arg(usr_args, "model_id")
        if not model_id:
            raise ValueError("model_id is required. Pass --model_id or set MODEL_ID.")

        checkpoints_dir = _resolve_file(_get_arg(usr_args, "checkpoints_dir"), wla_root)
        norm_file_path = _resolve_file(
            _get_arg(usr_args, "norm_file_path"),
            wla_root,
            default="configs/norm_stats.json",
        )

        action_chunk_size = _get_arg(usr_args, "action_chunk_size")
        if action_chunk_size in {None, "", "None", "none", "null"}:
            action_chunk_size = None
        else:
            action_chunk_size = int(action_chunk_size)

        return cls(
            wla_root=wla_root,
            model_id=_resolve_model_id(str(model_id), wla_root),
            checkpoints_dir=checkpoints_dir,
            norm_file_path=norm_file_path,
            unnorm_key=str(_required_arg(usr_args, "unnorm_key")),
            control_mode=control_mode,
            target_image_size=int(_get_arg(usr_args, "target_image_size", 512)),
            vae_downsample_f=int(_get_arg(usr_args, "vae_downsample_f", 32)),
            max_state_dim=int(_required_arg(usr_args, "max_state_dim")),
            original_action_dim=int(_required_arg(usr_args, "original_action_dim")),
            primary_image_size=int(_get_arg(usr_args, "primary_image_size", 256)),
            auxiliary_image_size=int(_get_arg(usr_args, "auxiliary_image_size", 256)),
            action_chunk_size=action_chunk_size,
            strip_world_model=_as_bool(_get_arg(usr_args, "strip_world_model"), True),
            dtype=str(_get_arg(usr_args, "dtype", "bfloat16")),
        )

    def reset(self):
        self.history_observation = None

    def _strip_unused_modules(self):
        for module_name in ("world_expert", "connector"):
            if hasattr(self.model.model, module_name):
                delattr(self.model.model, module_name)
        if hasattr(self.model, "vae"):
            delattr(self.model, "vae")

    def _encode_obs(self, observation: dict[str, Any]):
        obs = observation["observation"]

        head_camera_tensor = to_tensor(obs["head_camera"]["rgb"])
        left_camera_tensor = to_tensor(obs["left_camera"]["rgb"])
        right_camera_tensor = to_tensor(obs["right_camera"]["rgb"])

        if self.history_observation is None:
            history_head_camera_tensor = head_camera_tensor
        else:
            history_head_camera_tensor = to_tensor(
                self.history_observation["observation"]["head_camera"]["rgb"]
            )

        primary_image_transform = self.make_transform(self.primary_image_size)
        auxiliary_image_transform = self.make_transform(self.auxiliary_image_size)

        input_images = [[
            auxiliary_image_transform(history_head_camera_tensor),
            primary_image_transform(head_camera_tensor),
            auxiliary_image_transform(left_camera_tensor),
            auxiliary_image_transform(right_camera_tensor),
        ]]

        if self.control_mode == "eef":
            state = (
                _to_list(observation["endpose"]["left_endpose"])
                + _to_list(observation["endpose"]["left_gripper"])
                + _to_list(observation["endpose"]["right_endpose"])
                + _to_list(observation["endpose"]["right_gripper"])
            )
        else:
            state = _to_list(observation["joint_action"]["vector"])

        states = torch.tensor(state)
        states, _ = self.normalize_and_pad(
            states,
            self.norm_stats["observation.state"],
            self.max_state_dim,
        )

        return input_images, states.unsqueeze(0)

    def _postprocess_actions(self, actions: Any) -> torch.Tensor:
        actions = torch.as_tensor(actions)
        actions = self.unnormalize_and_unpad(
            actions,
            self.norm_stats["action"],
            self.original_action_dim,
        )

        if self.control_mode == "eef":
            left_quat = actions[:, 3:7]
            right_quat = actions[:, 11:15]
            left_norm = torch.linalg.norm(left_quat, dim=1, keepdim=True)
            right_norm = torch.linalg.norm(right_quat, dim=1, keepdim=True)
            actions = torch.cat(
                [
                    actions[:, :3],
                    left_quat / left_norm,
                    actions[:, 7:11],
                    right_quat / right_norm,
                    actions[:, 15:16],
                ],
                dim=1,
            )

        if self.action_chunk_size is not None:
            actions = actions[: self.action_chunk_size]
        return actions

    @torch.inference_mode()
    def _predict_actions(self, observation: dict[str, Any], instruction: str) -> torch.Tensor:
        input_images, states = self._encode_obs(observation)

        model_dtype = next(self.model.model.action_expert.parameters()).dtype
        model_device = next(self.model.model.action_expert.parameters()).device
        states = states.to(dtype=model_dtype, device=model_device)

        with torch.autocast(device_type="cuda", dtype=torch.bfloat16, enabled=model_device.type == "cuda"):
            actions = self.model.sample_actions(
                caption=instruction,
                input_images=input_images,
                num_images_per_prompt=1,
                states=states,
            )
        return self._postprocess_actions(actions)

    def eval_step(self, TASK_ENV, observation: dict[str, Any]):
        instruction = TASK_ENV.get_instruction()
        fast_eval = _configure_eval_observation(TASK_ENV)
        actions = self._predict_actions(observation, instruction)
        # `history_obs_step` is not a frame count: the model reads exactly one
        # history image (see _encode_obs). It only selects which post-action
        # observation carries over to the next chunk.
        target_history_index = max(len(actions) - self.history_obs_step - 1, 0)
        post_action_observation_indices = _post_action_observation_indices(
            len(actions), self.history_obs_step, fast_eval
        )

        last_observation = observation
        for index, action in enumerate(actions):
            action = action.detach().cpu().numpy()
            if self.control_mode == "eef":
                TASK_ENV.take_action(action, action_type="ee", render=not fast_eval)
            else:
                TASK_ENV.take_action(action, render=not fast_eval)
            if index in post_action_observation_indices:
                last_observation = TASK_ENV.get_obs()
                if index == target_history_index:
                    self.history_observation = last_observation

        if self.history_observation is None:
            self.history_observation = last_observation

        return self.history_observation
